language: c

sudo: required
dist: trusty

install:
 - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install
        gir1.2-gstreamer-1.0
        git
        make
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        valac

script:
 - make prefix=/usr
 - sudo make install prefix=/usr
